### ISSUE TITLE
HTTP Code: 403

### ISSUE THREAD

**Issue by xRTRx** [robertdebock/galaxy-action#12]
I have encountered a problem with galaxy-action. I am trying to push an Ansible role to the galaxy using this action, but I get an error message that says `ERROR! Error when finding available api versions from default (https://galaxy.ansible.com) (HTTP Code: 403, Message: Forbidden)`. 
This prevents me from uploading my role to the galaxy. I have checked the documentation and the examples, but I could not find a solution. Does anyone know how to fix this issue? Thank you for your help.

**Comment by bodsch** [comment]
Please also note that the Ansible team has released a new Galaxy version.
This has unpleasant side effects up to the unusability of the import function!

I have already published corresponding entries in the [Ansible forum](
https://forum.ansible.com/t/failed-role-import-to-galaxy-ng/1534).

**Comment by kirill-zak** [comment]
@josegonzalez sad that fix was [realized](https://github.com/dokku/ansible-dokku/issues/159#issuecomment-1879984945) at 07.01.2024

**Comment by josegonzalez** [comment]
@kirill-zak I'm not sure why you're sad, but its good to know it was released. I don't know if the [docker image this uses](https://github.com/robertdebock/docker-github-action-galaxy) has the correct version in it, but would be good to validate that as we're still seeing issues publishing it.
